// Generated by CoffeeScript 1.3.3
var LevelEndless, _base, _ref, _ref1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

if ((_ref = window.LD24) == null) {
  window.LD24 = {};
}

if ((_ref1 = (_base = window.LD24).Levels) == null) {
  _base.Levels = {};
}

window.LD24.Levels.LevelEndless = LevelEndless = (function(_super) {

  __extends(LevelEndless, _super);

  LevelEndless.prototype.subname = 'Endless Game Mode';

  function LevelEndless(game, scene, screen, level) {
    this.game = game;
    this.scene = scene;
    this.screen = screen;
    LevelEndless.__super__.constructor.call(this, this.game, this.scene, this.screen);
    this.name = 'Level ' + level;
    this.levelNumDisplayer.text(this.name);
  }

  return LevelEndless;

})(LD24.Level);
