// Generated by CoffeeScript 1.3.3
var Game, _ref;

if ((_ref = window.LD24) == null) {
  window.LD24 = {};
}

window.LD24.Game = Game = (function() {

  Game.prototype.framesPerSecond = 60;

  function Game(canvas) {
    var _this = this;
    this.canvas = canvas;
    this.screen = new LD24.Screen(this.canvas);
    this.scene = new LD24.Scenes.SplashScene(this, this.screen);
    this.sounds = new LD24.Sounds(this);
    this.setupTickLoop();
    this.setupRenderLoop();
    jwerty.key('p', function() {
      return _this.pause();
    });
  }

  Game.prototype.showInfoBox = function(message) {
    $('.info-box .text').text(message);
    $('.info-box').css({
      marginTop: -5,
      opacity: 0,
      display: 'block'
    });
    return $('.info-box').animate({
      marginTop: 0,
      opacity: 0.8
    }, 'slow');
  };

  Game.prototype.hideInfoBox = function(message) {
    return $('.info-box').fadeOut('fast');
  };

  Game.prototype.loadCampaign = function() {
    var _this = this;
    return this.scene.terminate(function() {
      return _this.scene = new LD24.Scenes.GameScene(_this, _this.screen);
    });
  };

  Game.prototype.setupTickLoop = function() {
    var _this = this;
    return this.tickLoop = every(1000 / this.framesPerSecond, function() {
      return _this.tick();
    });
  };

  Game.prototype.setupRenderLoop = function() {
    var _this = this;
    return this.renderLoop = every(1000 / this.framesPerSecond, function() {
      return _this.render();
    });
  };

  Game.prototype.tick = function() {
    return this.scene.tick();
  };

  Game.prototype.render = function() {
    this.screen.clear();
    return this.scene.render();
  };

  Game.prototype.pause = function() {
    clearInterval(this.tickLoop);
    return clearInterval(this.renderLoop);
  };

  Game.prototype.debug = function(msg) {
    return $('.debug').show().text(msg);
  };

  return Game;

})();
