// Generated by CoffeeScript 1.3.3
var Level, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

if ((_ref = window.LD24) == null) {
  window.LD24 = {};
}

window.LD24.Level = Level = (function(_super) {

  __extends(Level, _super);

  function Level(game, scene, screen) {
    this.game = game;
    this.scene = scene;
    this.screen = screen;
    this.progressDoneDisplayer = $('.progress .done');
    this.levelNumDisplayer = $('.level');
  }

  Level.prototype.addNormalMobs = function(count, scale) {
    var i, mob, _i, _results;
    _results = [];
    for (i = _i = 0; 0 <= count ? _i < count : _i > count; i = 0 <= count ? ++_i : --_i) {
      mob = new LD24.Mobs.Mote(this.game, this.scene, this.screen);
      mob.x = Math.random() * this.screen.width;
      mob.y = Math.random() * this.screen.height;
      mob.scale = mob.toScale = scale;
      mob.speedX = mob.toSpeedX = Math.random() * mob.maxSpeed;
      if (Math.round(Math.random()) === 0) {
        mob.speedX *= -1;
      }
      mob.speedY = mob.toSpeedY = Math.random() * mob.maxSpeed;
      if (Math.round(Math.random()) === 0) {
        mob.speedY *= -1;
      }
      _results.push(this.scene.mobs.push(mob));
    }
    return _results;
  };

  Level.prototype.addPowerUps = function(count) {
    var i, mob, _i, _results;
    _results = [];
    for (i = _i = 0; 0 <= count ? _i < count : _i > count; i = 0 <= count ? ++_i : --_i) {
      mob = new LD24.Mobs.PowerUp(this.game, this.scene, this.screen);
      mob.x = Math.random() * this.screen.width;
      mob.y = Math.random() * this.screen.height;
      mob.speedX = mob.toSpeedX = Math.random() * mob.maxSpeed;
      if (Math.round(Math.random()) === 0) {
        mob.speedX *= -1;
      }
      mob.speedY = mob.toSpeedY = Math.random() * mob.maxSpeed;
      if (Math.round(Math.random()) === 0) {
        mob.speedY *= -1;
      }
      _results.push(this.scene.mobs.push(mob));
    }
    return _results;
  };

  Level.prototype.addBadMobs = function(count, scale) {
    var i, mob, _i, _results;
    _results = [];
    for (i = _i = 0; 0 <= count ? _i < count : _i > count; i = 0 <= count ? ++_i : --_i) {
      mob = new LD24.Mobs.Bad(this.game, this.scene, this.screen);
      mob.x = Math.random() * this.screen.width;
      mob.y = Math.random() * this.screen.height;
      mob.scale = mob.scaleTo = scale;
      mob.speedX = mob.toSpeedX = Math.random() * mob.maxSpeed;
      if (Math.round(Math.random()) === 0) {
        mob.speedX *= -1;
      }
      mob.speedY = mob.toSpeedY = Math.random() * mob.maxSpeed;
      if (Math.round(Math.random()) === 0) {
        mob.speedY *= -1;
      }
      _results.push(this.scene.mobs.push(mob));
    }
    return _results;
  };

  return Level;

})(EventEmitter);
