// Generated by CoffeeScript 1.3.3
var Particle, _ref;

if ((_ref = window.LD24) == null) {
  window.LD24 = {};
}

window.LD24.Particle = Particle = (function() {

  function Particle(game, scene, screen) {
    this.game = game;
    this.scene = scene;
    this.screen = screen;
    this.x = 0;
    this.y = 0;
    this.speedX = 0;
    this.speedY = 0;
    this.scrollX = 0;
    this.scrollY = 0;
    this.spriteX = Math.round(Math.random());
    this.scale = Math.random() * 0.3;
  }

  Particle.prototype.tick = function() {
    this.x += this.speedX;
    return this.y += this.speedY;
  };

  Particle.prototype.render = function() {
    var finalH, finalW, finalX, finalY;
    this.scrollX += (this.scene.toScrollX - this.scene.scrollX) / (100 * (0.3 - this.scale));
    this.scrollY += (this.scene.toScrollY - this.scene.scrollY) / (100 * (0.3 - this.scale));
    finalW = 32 * this.scene.zoom * this.scale;
    finalH = 32 * this.scene.zoom * this.scale;
    finalX = this.x * this.scene.zoom - this.scrollX;
    finalY = this.y * this.scene.zoom - this.scrollY;
    return this.screen.render(768 + this.spriteX * 32, 0, 32, 32, finalX, finalY, finalW, finalH);
  };

  return Particle;

})();
