// Generated by CoffeeScript 1.3.3
var Screen, _ref;

if ((_ref = window.LD24) == null) {
  window.LD24 = {};
}

window.LD24.Screen = Screen = (function() {

  function Screen(game, canvas) {
    var _this = this;
    this.game = game;
    this.canvas = canvas;
    this.context = this.canvas.get(0).getContext('2d');
    this.canvas.get(0).width = this.width = this.canvas.width();
    this.canvas.get(0).height = this.height = this.canvas.height();
    this.sprites = new Image;
    this.sprites.src = 'assets/images/sprites.png';
    this.sprites.onload = function() {
      return console.log("sprites loaded");
    };
  }

  Screen.prototype.clear = function() {
    return this.context.fillRect(0, 0, this.width, this.height);
  };

  Screen.prototype.render = function(sx, sy, sw, sh, dx, dy, dw, dh) {
    if (dw == null) {
      dw = sw;
    }
    if (dh == null) {
      dh = sh;
    }
    return this.context.drawImage(this.sprites, sx, sy, sw, sh, dx, dy, dw, dh);
  };

  return Screen;

})();
