// Generated by CoffeeScript 1.3.3
var Sounds, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

if ((_ref = window.LD24) == null) {
  window.LD24 = {};
}

window.LD24.Sounds = Sounds = (function(_super) {

  __extends(Sounds, _super);

  function Sounds(game) {
    var _this = this;
    this.game = game;
    soundManager.setup({
      debugMode: false,
      url: 'assets/swf/',
      onready: function() {
        return _this.loadSounds();
      }
    });
  }

  Sounds.prototype.loadSounds = function() {
    var file, filesLoaded, filesToLoad, name, options, sound, _ref1, _results,
      _this = this;
    this.sounds = {
      absorb: {
        files: ['absorb_1', 'absorb_2', 'absorb_3'],
        sounds: []
      }
    };
    filesLoaded = 0;
    filesToLoad = 4;
    this.soundtrack = soundManager.createSound({
      id: 'soundtrack',
      url: ['assets/audio/absorption.mp3', 'assets/audio/absorption.aac', 'assets/audio/absorption.ogg'],
      autoLoad: true,
      autoPlay: false,
      onload: function() {
        filesLoaded++;
        if (filesLoaded === filesToLoad) {
          return _this.emit('loaded');
        }
      },
      onfinish: function() {
        return _this.playSoundtrack();
      }
    });
    _ref1 = this.sounds;
    _results = [];
    for (name in _ref1) {
      options = _ref1[name];
      _results.push((function() {
        var _i, _len, _ref2, _results1,
          _this = this;
        _ref2 = options.files;
        _results1 = [];
        for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
          file = _ref2[_i];
          sound = soundManager.createSound({
            id: file,
            url: ['assets/audio/' + file + '.mp3', 'assets/audio/' + file + '.aac', 'assets/audio/' + file + '.ogg'],
            autoLoad: true,
            autoPlay: false,
            onload: function() {
              filesLoaded++;
              if (filesLoaded === filesToLoad) {
                return _this.emit('loaded');
              }
            }
          });
          _results1.push(options.sounds.push(sound));
        }
        return _results1;
      }).call(this));
    }
    return _results;
  };

  Sounds.prototype.playSound = function(id) {
    var sounds;
    sounds = this.sounds[id].sounds;
    return _.shuffle(sounds)[0].play();
  };

  Sounds.prototype.playSoundtrack = function() {
    return this.soundtrack.play();
  };

  return Sounds;

})(EventEmitter);
