// Generated by CoffeeScript 1.3.3

window.every = function(t, f) {
  return setInterval(f, t);
};

window.after = function(t, f) {
  return setTimeout(f, t);
};

$(function() {
  var game;
  return game = window.game = new LD24.Game($('canvas'));
});
