// Generated by CoffeeScript 1.3.3
var Mob, _base, _ref, _ref1;

if ((_ref = window.LD24) == null) {
  window.LD24 = {};
}

if ((_ref1 = (_base = window.LD24).Mobs) == null) {
  _base.Mobs = {};
}

window.LD24.Mobs.Mob = Mob = (function() {

  Mob.prototype.spriteX = 16;

  Mob.prototype.spriteY = 0;

  Mob.prototype.spriteW = 16;

  Mob.prototype.spriteH = 16;

  function Mob(game, scene, screen) {
    this.game = game;
    this.scene = scene;
    this.screen = screen;
    this.x = 0;
    this.y = this.screen.height - this.scene.fragment.floorHeight - this.spriteH;
    this.removed = false;
  }

  Mob.prototype.tick = function() {};

  Mob.prototype.render = function() {
    return this.screen.render(this.spriteX, this.spriteY, this.spriteW, this.spriteH, this.x + this.scene.offsetX, this.y);
  };

  Mob.prototype.remove = function() {
    return this.removed = true;
  };

  Mob.prototype.intersects = function(mob) {
    if (this.x + this.spriteW < mob.x || this.x > mob.x + mob.spriteW || this.y + this.spriteH < mob.y || this.y > mob.y + mob.spriteH) {
      return false;
    }
    return true;
  };

  return Mob;

})();
