// Generated by CoffeeScript 1.3.3
var MoteMob, _base, _ref, _ref1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

if ((_ref = window.LD24) == null) {
  window.LD24 = {};
}

if ((_ref1 = (_base = window.LD24).Mobs) == null) {
  _base.Mobs = {};
}

window.LD24.Mobs.Mote = MoteMob = (function(_super) {

  __extends(MoteMob, _super);

  function MoteMob(game, scene, screen) {
    this.game = game;
    this.scene = scene;
    this.screen = screen;
    MoteMob.__super__.constructor.call(this, this.game, this.scene, this.screen);
  }

  return MoteMob;

})(LD24.Mob);
