// Generated by CoffeeScript 1.3.3
var PowerUpSpeedMob, _base, _ref, _ref1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

if ((_ref = window.LD24) == null) {
  window.LD24 = {};
}

if ((_ref1 = (_base = window.LD24).Mobs) == null) {
  _base.Mobs = {};
}

window.LD24.Mobs.PowerUpSpeed = PowerUpSpeedMob = (function(_super) {

  __extends(PowerUpSpeedMob, _super);

  function PowerUpSpeedMob(game, scene, screen) {
    this.game = game;
    this.scene = scene;
    this.screen = screen;
    PowerUpSpeedMob.__super__.constructor.call(this, this.game, this.scene, this.screen);
  }

  PowerUpSpeedMob.prototype.absorbedBy = function(mob) {
    PowerUpSpeedMob.__super__.absorbedBy.call(this, mob);
    mob.powerupSpeed = true;
    mob.powerupSpeedEndTick = mob.tickCount + 60 * 10;
    return mob.maxSpeed = 3;
  };

  return PowerUpSpeedMob;

})(LD24.Mobs.PowerUp);
