// Generated by CoffeeScript 1.3.3
var PowerUpMob, _base, _ref, _ref1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

if ((_ref = window.LD24) == null) {
  window.LD24 = {};
}

if ((_ref1 = (_base = window.LD24).Mobs) == null) {
  _base.Mobs = {};
}

window.LD24.Mobs.PowerUp = PowerUpMob = (function(_super) {

  __extends(PowerUpMob, _super);

  function PowerUpMob(game, scene, screen) {
    this.game = game;
    this.scene = scene;
    this.screen = screen;
    PowerUpMob.__super__.constructor.call(this, this.game, this.scene, this.screen);
    this.opacity = 1.0;
    this.borderRotation = 0;
  }

  PowerUpMob.prototype.tick = function() {
    PowerUpMob.__super__.tick.call(this);
    return this.borderRotation += 0.8;
  };

  PowerUpMob.prototype.render = function() {
    var finalH, finalW, finalX, finalY;
    finalW = this.spriteW * this.scale * this.scene.zoom;
    finalH = this.spriteH * this.scale * this.scene.zoom;
    finalX = (this.x * this.scene.zoom - finalW / 2) - this.scene.scrollX;
    finalY = (this.y * this.scene.zoom - finalH / 2) - this.scene.scrollY;
    this.screen.render(256, 256, 256, 256, finalX, finalY, finalW, finalH);
    this.screen.render(256 * 2, 256, 256, 256, finalX - this.speedX * 10, finalY - this.speedY * 10, finalW, finalH, this.rotation * (Math.PI / 180));
    this.screen.render(256 * 3, 256, 256, 256, finalX - this.speedX * 10, finalY - this.speedY * 10, finalW, finalH, this.rotation * (Math.PI / 180));
    return this.screen.render(0, 512, 256, 256, finalX - this.speedX * 10, finalY - this.speedY * 10, finalW, finalH, this.borderRotation * (Math.PI / 180));
  };

  PowerUpMob.prototype.canBeAbsorbedBy = function(mob) {
    if (mob.scale > this.scale && mob instanceof LD24.Mobs.Player) {
      return true;
    }
    return false;
  };

  return PowerUpMob;

})(LD24.Mob);
