// Generated by CoffeeScript 1.3.3
var BasicFragment, _base, _ref, _ref1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

if ((_ref = window.LD24) == null) {
  window.LD24 = {};
}

if ((_ref1 = (_base = window.LD24).Fragments) == null) {
  _base.Fragments = {};
}

window.LD24.Fragments.Basic = BasicFragment = (function(_super) {

  __extends(BasicFragment, _super);

  BasicFragment.prototype.width = 9000;

  BasicFragment.prototype.floorHeight = 16;

  function BasicFragment(game, scene, screen) {
    this.game = game;
    this.scene = scene;
    this.screen = screen;
  }

  BasicFragment.prototype.tick = function() {};

  BasicFragment.prototype.render = function() {
    var drawX, i, _i, _ref2, _results;
    _results = [];
    for (i = _i = 0, _ref2 = this.width / 16; 0 <= _ref2 ? _i < _ref2 : _i > _ref2; i = 0 <= _ref2 ? ++_i : --_i) {
      drawX = i * 16 + this.scene.offsetX;
      if (drawX > -15 && drawX < this.screen.width) {
        _results.push(this.screen.render(0, 0, 16, 16, drawX, this.screen.height - 16));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  return BasicFragment;

})(LD24.Fragments.Fragment);
