// Generated by CoffeeScript 1.3.3
var EightBitFragment, _base, _ref, _ref1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

if ((_ref = window.LD24) == null) {
  window.LD24 = {};
}

if ((_ref1 = (_base = window.LD24).Fragments) == null) {
  _base.Fragments = {};
}

window.LD24.Fragments.EightBit = EightBitFragment = (function(_super) {

  __extends(EightBitFragment, _super);

  EightBitFragment.prototype.width = 3000;

  EightBitFragment.prototype.floorHeight = 16;

  EightBitFragment.prototype.gfx = {
    player: {
      frames: 4,
      spriteY: 32,
      spriteXOffset: 16
    },
    mob: {
      frames: 4,
      spriteY: 32,
      spriteXOffset: 16 * 5
    },
    font: {
      spriteY: 48
    }
  };

  function EightBitFragment(game, scene, screen) {
    this.game = game;
    this.scene = scene;
    this.screen = screen;
    this.offsetX = 0;
  }

  EightBitFragment.prototype.tick = function() {};

  EightBitFragment.prototype.render = function() {
    var drawX, i, _i, _ref2, _results;
    _results = [];
    for (i = _i = 0, _ref2 = this.width / 16; 0 <= _ref2 ? _i < _ref2 : _i > _ref2; i = 0 <= _ref2 ? ++_i : --_i) {
      drawX = i * 16 + this.offsetX;
      if (drawX > -16 && drawX < this.screen.width) {
        _results.push(this.screen.render(0, 32, 16, 16, drawX, this.screen.height - 16));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  return EightBitFragment;

})(LD24.Fragments.Fragment);
