// Generated by CoffeeScript 1.3.3
var Fragment, _base, _ref, _ref1;

if ((_ref = window.LD24) == null) {
  window.LD24 = {};
}

if ((_ref1 = (_base = window.LD24).Fragments) == null) {
  _base.Fragments = {};
}

window.LD24.Fragments.Fragment = Fragment = (function() {

  Fragment.prototype.width = 1000;

  function Fragment(game, scene, screen) {
    this.game = game;
    this.scene = scene;
    this.screen = screen;
    this.offsetX = 0;
  }

  Fragment.prototype.tick = function() {
    return null;
  };

  Fragment.prototype.render = function() {
    return null;
  };

  return Fragment;

})();
